# Generated by Django 2.1.5 on 2019-04-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChlenKomissii',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО Члена комиссии')),
                ('udost_type', models.CharField(choices=[('Персонал', 'Персонал'), ('Материалы', 'Материалы'), ('Оборудование', 'Оборудование'), ('Технологии', 'Технологии'), ('Оценка квалификации', 'Оценка квалификации')], default='Персонал', max_length=2, verbose_name='Тип удостоверения')),
                ('udost_number', models.CharField(max_length=20, verbose_name='Номер удостоверения')),
                ('udost_gtu', models.CharField(max_length=100, verbose_name='Область распространения (ГТУ)')),
                ('udost_sp_sv', models.CharField(max_length=200, verbose_name='Область аттестации(способы сварки, материалы и т.д.)')),
            ],
        ),
    ]
