# Generated by Django 2.1.5 on 2019-04-09 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_chlenkomissii'),
    ]

    operations = [
        migrations.AddField(
            model_name='chlenkomissii',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.Tag'),
        ),
    ]
